### ISSUE TITLE
Any plan to put this on Bower/NPM?

### ISSUE THREAD

**Issue by mmmeff** [awulder/angular-prismicio#24]
Love the lib, especially the prismicHtml directive!!!

Would love to remove your lib from my repo, though. Did you have any plans to push this up to Bower (or other similar services)?

**Comment by jajourda** [comment]
if you want to include this via bower you can add the following to your bowser.json file dependencies object: "dependencies": {
... ,
 "angular-prismicio": "https://github.com/awulder/angular-prismicio.git"
}

**Comment by mmmeff** [comment]
True, but is there a reason you haven't submitted it to the global package list?

**Comment by awulder** [comment]
It is registered as a Bower package, http://bower.io/search/?q=angular-prismicio.
```bower install angular-prismicio``` should work

**Comment by mmmeff** [comment]
Ah, figured it wasn't because it's not in the readme. :+1:

**Comment by jajourda** [comment]
it does work :) just reinstalled via bower to test on existing project.
