### ISSUE TITLE
Getting cors error

### ISSUE THREAD

**Issue by swrocket** [awulder/angular-prismicio#29]
I'm trying to use the service but getting an error about access control

OPTIONS https://lesbonneschoses.prismic.io/api (anonymous function) @ angular.js:10695sendReq @ angular.js:10514status.$get.serverRequest @ angular.js:10221processQueue @ angular.js:14678(anonymous function) @ angular.js:14694parent.$get.Scope.$eval @ angular.js:15922parent.$get.Scope.$digest @ angular.js:15733parent.$get.Scope.$apply @ angular.js:16030done @ angular.js:10545completeRequest @ angular.js:10717requestLoaded @ angular.js:10658
(index):1 XMLHttpRequest cannot load https://lesbonneschoses.prismic.io/api. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access. The response had HTTP status code 404.

I'm assuming there is an underlying error, but not sure what to do here.

TIA

Andrew

**Comment by swrocket** [comment]
for now I disabled the satellizer interceptor and it's working

**Comment by arg20** [comment]
I'm having this issue but not using satellizer
